const constants = {
	PICK_LEVEL: "PICK_LEVEL",
	GUESS_WORD: "GUESS_WORD",
	CORRECT_POS: "CORRECT_POS",
	ADD_TO_HISTORY: "ADD_TO_HISTORY",
	CLEAR_HISTORY: "CLEAR_HISTORY",
	TOTAL_CHANCES: 5,
	RESTART: "RESTART",
	VERY_EASY: 6,
	EASY: 7,
	AVERAGE: 8,
	HARD: 9,
	VERY_HARD: 10
}

export default constants