const constants = {
	PICK_LEVEL: "PICK_LEVEL",
	GUESS_WORD: "GUESS_WORD",
	CORRECT_POS: "CORRECT_POS",
	ADD_TO_HISTORY: "ADD_TO_HISTORY",
	CLEAR_HISTORY: "CLEAR_HISTORY",
	TOTAL_CHANCES: 5,
	RESTART: "RESTART"
	// SET_GOAL: "SET_GOAL",
	// ADD_ERROR: "ADD_ERROR",
	// CLEAR_ERROR: "CLEAR_ERROR",
	// FETCH_RESORT_NAMES: "FETCH_RESORT_NAMES",
	// CANCEL_FETCHING: "CANCEL_FETCHING",
	// CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
	// CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS"
}

export default constants